package Client.View;

import java.awt.event.ActionListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Thien Nguyen
 */
public class CustomerGUI extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * Creates new form CustomerGUI
     */
	public CustomerGUI() {
        initComponents();
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
        jLabel14 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        searchPane = new javax.swing.JPanel();
        searchLabel = new javax.swing.JLabel();
        clientidButton = new javax.swing.JRadioButton();
        searchPrompt = new javax.swing.JLabel();
        lastButton = new javax.swing.JRadioButton();
        typeButton = new javax.swing.JRadioButton();
        paramPrompt = new javax.swing.JLabel();
        paramField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        resultPane = new javax.swing.JPanel();
        resultLabel = new javax.swing.JLabel();
        resultScroll = new javax.swing.JScrollPane();
        resultField = new javax.swing.JTextArea();
        infoPane = new javax.swing.JPanel();
        infoLabel = new javax.swing.JLabel();
        custidLabel = new javax.swing.JLabel();
        firstLabel = new javax.swing.JLabel();
        lastLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        postalLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        lastField = new javax.swing.JTextField();
        custidField = new javax.swing.JTextField();
        firstField = new javax.swing.JTextField();
        postalField = new javax.swing.JTextField();
        AddressField = new javax.swing.JTextField();
        phoneField = new javax.swing.JTextField();
        typeField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        messagePane = new javax.swing.JPanel();
        messageLabel = new javax.swing.JLabel();
        messageScroll = new javax.swing.JScrollPane();
        messageField = new javax.swing.JTextArea();

        jLabel14.setText("jLabel14");
        

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(805, 508));
        setResizable(false);

        header.setBackground(new java.awt.Color(153, 153, 255));

        headerLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        headerLabel.setText("Customer Management System");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(headerLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(headerLabel)
                .addContainerGap())
        );

        searchPane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 3, true));

        searchLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        searchLabel.setText("Customer Search");

        clientidButton.setText("Client ID");
     

        searchPrompt.setText("Select type of search to be performed:");

        lastButton.setText("Last Name");

        typeButton.setText("Client Type");

        paramPrompt.setText("Enter Search Parameter");
        searchButton.setText("Search");
        javax.swing.GroupLayout searchPaneLayout = new javax.swing.GroupLayout(searchPane);
        searchPane.setLayout(searchPaneLayout);
        searchPaneLayout.setHorizontalGroup(
            searchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPaneLayout.createSequentialGroup()
                .addGroup(searchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(paramPrompt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paramField))
                    .addGroup(searchPaneLayout.createSequentialGroup()
                        .addGroup(searchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(searchPaneLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(searchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(searchPrompt)
                                    .addComponent(clientidButton)
                                    .addComponent(lastButton)
                                    .addComponent(typeButton)))
                            .addGroup(searchPaneLayout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(searchLabel)))
                        .addGap(0, 87, Short.MAX_VALUE))
                .addGroup(searchPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(paramPrompt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(searchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(searchPaneLayout.createSequentialGroup()
                                .addComponent(searchButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(paramField))))
                .addContainerGap())
        );
        searchPaneLayout.setVerticalGroup(
            searchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPaneLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(searchLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchPrompt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clientidButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(typeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(searchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(paramPrompt)
                .addComponent(paramField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        resultPane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 3, true));

        resultLabel.setText("Search Result:");

        resultField.setColumns(20);
        resultField.setRows(5);
        resultScroll.setViewportView(resultField);

        javax.swing.GroupLayout resultPaneLayout = new javax.swing.GroupLayout(resultPane);
        resultPane.setLayout(resultPaneLayout);
        resultPaneLayout.setHorizontalGroup(
            resultPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(resultPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultScroll)
                    .addGroup(resultPaneLayout.createSequentialGroup()
                        .addComponent(resultLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        resultPaneLayout.setVerticalGroup(
            resultPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addContainerGap())
        );

        infoPane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 3, true));

        infoLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        infoLabel.setText("Customer Information");

        custidLabel.setText("Customer ID:");

        firstLabel.setText("First Name:");

        lastLabel.setText("Last Name:");

        addressLabel.setText("Address:");

        postalLabel.setText("Postal Code:");

        phoneLabel.setText("Phone:");

        typeLabel.setText("Customer Type:");

        

        saveButton.setText("Save");
  
        

        deleteButton.setText("Delete");

        clearButton.setText("Clear");

        javax.swing.GroupLayout infoPaneLayout = new javax.swing.GroupLayout(infoPane);
        infoPane.setLayout(infoPaneLayout);
        infoPaneLayout.setHorizontalGroup(
            infoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(infoLabel)
                .addGap(107, 107, 107))
            .addGroup(infoPaneLayout.createSequentialGroup()
                .addGroup(infoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(infoPaneLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearButton))
                    .addGroup(infoPaneLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(infoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPaneLayout.createSequentialGroup()
                                .addComponent(typeLabel)
                                .addGap(18, 18, 18)
                                .addComponent(typeField, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(infoPaneLayout.createSequentialGroup()
                                .addGroup(infoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addressLabel)
                                    .addComponent(lastLabel)
                                    .addComponent(firstLabel)
                                    .addComponent(custidLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(infoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(custidField, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                    .addComponent(firstField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lastField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AddressField, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(infoPaneLayout.createSequentialGroup()
                                .addGroup(infoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(postalLabel)
                                    .addComponent(phoneLabel))
                                .addGap(39, 39, 39)
                                .addGroup(infoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(phoneField, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                    .addComponent(postalField))))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        infoPaneLayout.setVerticalGroup(
            infoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoLabel)
                .addGap(18, 18, 18)
                .addGroup(infoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(custidLabel)
                    .addComponent(custidField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(infoPaneLayout.createSequentialGroup()
                        .addComponent(firstLabel)
                        .addGap(100, 100, 100))
                    .addGroup(infoPaneLayout.createSequentialGroup()
                        .addComponent(firstField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(infoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(infoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addressLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(infoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(postalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(postalLabel))))
                .addGroup(infoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLabel)
                    .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeLabel)
                    .addComponent(typeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(deleteButton)
                    .addComponent(clearButton))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        messagePane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 3, true));

        messageLabel.setText("Message:");

        messageField.setColumns(20);
        messageField.setRows(5);
        messageScroll.setViewportView(messageField);

        javax.swing.GroupLayout messagePaneLayout = new javax.swing.GroupLayout(messagePane);
        messagePane.setLayout(messagePaneLayout);
        messagePaneLayout.setHorizontalGroup(
            messagePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messagePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(messageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(messageScroll)
                .addContainerGap())
        );
        messagePaneLayout.setVerticalGroup(
            messagePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messagePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(messagePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(messageScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(messageLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resultPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(infoPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(messagePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resultPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(infoPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(messagePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public javax.swing.JTextField getAddressField() {
		return AddressField;
	}

	public void setAddressField(javax.swing.JTextField addressField) {
		AddressField = addressField;
	}

	public javax.swing.JLabel getAddressLabel() {
		return addressLabel;
	}

	public void setAddressLabel(javax.swing.JLabel addressLabel) {
		this.addressLabel = addressLabel;
	}

	public javax.swing.JButton getClearButton() {
		return clearButton;
	}

	public void setClearButton(javax.swing.JButton clearButton) {
		this.clearButton = clearButton;
	}

	public javax.swing.JRadioButton getClientidButton() {
		return clientidButton;
	}

	public void setClientidButton(javax.swing.JRadioButton clientidButton) {
		this.clientidButton = clientidButton;
	}

	public javax.swing.JTextField getCustidField() {
		return custidField;
	}

	public void setCustidField(javax.swing.JTextField custidField) {
		this.custidField = custidField;
	}

	public javax.swing.JLabel getCustidLabel() {
		return custidLabel;
	}

	public void setCustidLabel(javax.swing.JLabel custidLabel) {
		this.custidLabel = custidLabel;
	}

	public javax.swing.JButton getDeleteButton() {
		return deleteButton;
	}

	public void setDeleteButton(javax.swing.JButton deleteButton) {
		this.deleteButton = deleteButton;
	}

	public javax.swing.JTextField getFirstField() {
		return firstField;
	}

	public void setFirstField(javax.swing.JTextField firstField) {
		this.firstField = firstField;
	}

	public javax.swing.JLabel getFirstLabel() {
		return firstLabel;
	}

	public void setFirstLabel(javax.swing.JLabel firstLabel) {
		this.firstLabel = firstLabel;
	}

	public javax.swing.JPanel getHeader() {
		return header;
	}

	public void setHeader(javax.swing.JPanel header) {
		this.header = header;
	}

	public javax.swing.JLabel getHeaderLabel() {
		return headerLabel;
	}

	public void setHeaderLabel(javax.swing.JLabel headerLabel) {
		this.headerLabel = headerLabel;
	}

	public javax.swing.JLabel getInfoLabel() {
		return infoLabel;
	}

	public void setInfoLabel(javax.swing.JLabel infoLabel) {
		this.infoLabel = infoLabel;
	}

	public javax.swing.JPanel getInfoPane() {
		return infoPane;
	}

	public void setInfoPane(javax.swing.JPanel infoPane) {
		this.infoPane = infoPane;
	}

	public javax.swing.JLabel getjLabel14() {
		return jLabel14;
	}

	public void setjLabel14(javax.swing.JLabel jLabel14) {
		this.jLabel14 = jLabel14;
	}

	public javax.swing.JTextArea getResultField() {
		return resultField;
	}

	public void setjTextArea1(javax.swing.JTextArea jTextArea1) {
		this.resultField = jTextArea1;
	}

	public javax.swing.JTextArea getMessageField() {
		return messageField;
	}

	public void setjTextArea2(javax.swing.JTextArea messageField) {
		this.messageField = messageField;
	}

	public javax.swing.JRadioButton getLastButton() {
		return lastButton;
	}

	public void setLastButton(javax.swing.JRadioButton lastButton) {
		this.lastButton = lastButton;
	}

	public javax.swing.JTextField getLastField() {
		return lastField;
	}

	public void setLastField(javax.swing.JTextField lastField) {
		this.lastField = lastField;
	}

	public javax.swing.JLabel getLastLabel() {
		return lastLabel;
	}

	public void setLastLabel(javax.swing.JLabel lastLabel) {
		this.lastLabel = lastLabel;
	}

	public javax.swing.JScrollPane getMessageScroll() {
		return messageScroll;
	}

	public void setMessageScroll(javax.swing.JScrollPane messageScroll) {
		this.messageScroll = messageScroll;
	}

	public javax.swing.JLabel getMessageLabel() {
		return messageLabel;
	}

	public void setMessageLabel(javax.swing.JLabel messageLabel) {
		this.messageLabel = messageLabel;
	}

	public javax.swing.JPanel getMessagePane() {
		return messagePane;
	}

	public void setMessagePane(javax.swing.JPanel messagePane) {
		this.messagePane = messagePane;
	}

	public javax.swing.JTextField getParamField() {
		return paramField;
	}

	public void setParamField(javax.swing.JTextField paramField) {
		this.paramField = paramField;
	}

	public javax.swing.JLabel getParamPrompt() {
		return paramPrompt;
	}

	public void setParamPrompt(javax.swing.JLabel paramPrompt) {
		this.paramPrompt = paramPrompt;
	}

	public javax.swing.JTextField getPhoneField() {
		return phoneField;
	}

	public void setPhoneField(javax.swing.JTextField phoneField) {
		this.phoneField = phoneField;
	}

	public javax.swing.JLabel getPhoneLabel() {
		return phoneLabel;
	}

	public void setPhoneLabel(javax.swing.JLabel phoneLabel) {
		this.phoneLabel = phoneLabel;
	}

	public javax.swing.JTextField getPostalField() {
		return postalField;
	}

	public void setPostalField(javax.swing.JTextField postalField) {
		this.postalField = postalField;
	}

	public javax.swing.JLabel getPostalLabel() {
		return postalLabel;
	}

	public void setPostalLabel(javax.swing.JLabel postalLabel) {
		this.postalLabel = postalLabel;
	}

	public javax.swing.JScrollPane getResulScroll() {
		return resultScroll;
	}

	public void setResultField(javax.swing.JScrollPane resultField) {
		this.resultScroll = resultField;
	}

	public javax.swing.JLabel getResultLabel() {
		return resultLabel;
	}

	public void setResultLabel(javax.swing.JLabel resultLabel) {
		this.resultLabel = resultLabel;
	}

	public javax.swing.JPanel getResultPane() {
		return resultPane;
	}

	public void setResultPane(javax.swing.JPanel resultPane) {
		this.resultPane = resultPane;
	}

	public javax.swing.JButton getSaveButton() {
		return saveButton;
	}

	public void setSaveButton(javax.swing.JButton saveButton) {
		this.saveButton = saveButton;
	}

	public javax.swing.JLabel getSearchLabel() {
		return searchLabel;
	}

	public void setSearchLabel(javax.swing.JLabel searchLabel) {
		this.searchLabel = searchLabel;
	}

	public javax.swing.JPanel getSearchPane() {
		return searchPane;
	}

	public void setSearchPane(javax.swing.JPanel searchPane) {
		this.searchPane = searchPane;
	}

	public javax.swing.JLabel getSearchPrompt() {
		return searchPrompt;
	}

	public void setSearchPrompt(javax.swing.JLabel searchPrompt) {
		this.searchPrompt = searchPrompt;
	}

	public javax.swing.JRadioButton getTypeButton() {
		return typeButton;
	}

	public void setTypeButton(javax.swing.JRadioButton typeButton) {
		this.typeButton = typeButton;
	}

	public javax.swing.JTextField getTypeField() {
		return typeField;
	}

	public void setTypeField(javax.swing.JTextField typeField) {
		this.typeField = typeField;
	}

	public javax.swing.JLabel getTypeLabel() {
		return typeLabel;
	}

	public void setTypeLabel(javax.swing.JLabel typeLabel) {
		this.typeLabel = typeLabel;
	}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressField;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JButton clearButton;
    private javax.swing.JRadioButton clientidButton;
    private javax.swing.JTextField custidField;
    private javax.swing.JLabel custidLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField firstField;
    private javax.swing.JLabel firstLabel;
    private javax.swing.JPanel header;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JPanel infoPane;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JTextArea resultField;
    private javax.swing.JTextArea messageField;
    private javax.swing.JRadioButton lastButton;
    private javax.swing.JTextField lastField;
    private javax.swing.JLabel lastLabel;
    private javax.swing.JScrollPane messageScroll;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JPanel messagePane;
    private javax.swing.JTextField paramField;
    private javax.swing.JLabel paramPrompt;
    private javax.swing.JTextField phoneField;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField postalField;
    private javax.swing.JLabel postalLabel;
    private javax.swing.JScrollPane resultScroll;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JPanel resultPane;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JPanel searchPane;
    private javax.swing.JLabel searchPrompt;
    private javax.swing.JRadioButton typeButton;
    private javax.swing.JTextField typeField;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
    
    public void addButtonListener(ActionListener id,ActionListener last,ActionListener type,
    								ActionListener search, ActionListener save,
    								ActionListener delete, ActionListener clear) {
    	clientidButton.addActionListener(id);
    	lastButton.addActionListener(last);
    	typeButton.addActionListener(type);
    	searchButton.addActionListener(search);
    	saveButton.addActionListener(save);
    	deleteButton.addActionListener(delete);
    	clearButton.addActionListener(clear);
    }
}

