package Client.View;

import java.awt.event.ActionListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author thiennguyen
 */
public class InventoryGUI extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form ToolGUI
     */
    public InventoryGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        toolBanner = new javax.swing.JPanel();
        toolBannerLabel = new javax.swing.JLabel();
        optionPane = new javax.swing.JPanel();
        listAllButton = new javax.swing.JButton();
        searchNameButton = new javax.swing.JButton();
        searchIDButton = new javax.swing.JButton();
        searchQuantButton = new javax.swing.JButton();
        decreaseButton = new javax.swing.JButton();
        addDeleteButton = new javax.swing.JButton();
        resultPane = new javax.swing.JPanel();
        resultLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();
        promptPane = new javax.swing.JLayeredPane();
        promptIDPane = new javax.swing.JPanel();
        enterIDLabel = new javax.swing.JLabel();
        enterIDField = new javax.swing.JTextField();
        enterIDSubmit = new javax.swing.JButton();
        promptNamePane = new javax.swing.JPanel();
        promptNameLabel = new javax.swing.JLabel();
        promptNameField = new javax.swing.JTextField();
        promptNameSubmit = new javax.swing.JButton();
        promptQtyPane = new javax.swing.JPanel();
        promptToolLabel = new javax.swing.JLabel();
        promptToolField = new javax.swing.JTextField();
        promptQtySubmit = new javax.swing.JButton();
        promptQtyLabel = new javax.swing.JLabel();
        promptQtyField = new javax.swing.JTextField();
        addDeletePanel = new javax.swing.JPanel();
        aDName = new javax.swing.JLabel();
        adNameField = new javax.swing.JTextField();
        deleteButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        aDID = new javax.swing.JLabel();
        aDIDField = new javax.swing.JTextField();
        aDQty = new javax.swing.JLabel();
        aDTypeField = new javax.swing.JTextField();
        aDType = new javax.swing.JLabel();
        adQtyField = new javax.swing.JTextField();
        aDPrice = new javax.swing.JLabel();
        aDPriceField = new javax.swing.JTextField();
        aDSupply = new javax.swing.JLabel();
        aDSupplyField = new javax.swing.JTextField();
        aDPower = new javax.swing.JLabel();
        aDPowerField = new javax.swing.JTextField();
        messagePane = new javax.swing.JPanel();
        messageLabel = new javax.swing.JLabel();
        messageArea = new javax.swing.JScrollPane();
        messageBox = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        toolBanner.setBackground(new java.awt.Color(153, 153, 255));

        toolBannerLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        toolBannerLabel.setText("Inventory Management System");

        javax.swing.GroupLayout toolBannerLayout = new javax.swing.GroupLayout(toolBanner);
        toolBanner.setLayout(toolBannerLayout);
        toolBannerLayout.setHorizontalGroup(
            toolBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolBannerLayout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(toolBannerLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        toolBannerLayout.setVerticalGroup(
            toolBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolBannerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(toolBannerLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        optionPane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 2, true));

        listAllButton.setText("List All Tools");

        searchNameButton.setText("Search by Tool Name");

        searchIDButton.setText("Search by Tool ID");

        searchQuantButton.setText("Check Tool Quantity");

        decreaseButton.setText("Decrease Item Quantity");

        addDeleteButton.setText("Add/Delete Item");

        javax.swing.GroupLayout optionPaneLayout = new javax.swing.GroupLayout(optionPane);
        optionPane.setLayout(optionPaneLayout);
        optionPaneLayout.setHorizontalGroup(
            optionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPaneLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(optionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(decreaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchQuantButton)
                    .addComponent(searchIDButton, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(optionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(searchNameButton)
                        .addComponent(listAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        optionPaneLayout.setVerticalGroup(
            optionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listAllButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchNameButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchIDButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchQuantButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(decreaseButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addDeleteButton)
                .addGap(12, 12, 12))
        );

        resultPane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 2, true));

        resultLabel.setText("Result:");

        resultTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        resultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tool_id", "Name", "Type", "Quantity", "Price", "Supplier_id", "Power"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(resultTable);
        if (resultTable.getColumnModel().getColumnCount() > 0) {
            resultTable.getColumnModel().getColumn(2).setResizable(false);
            resultTable.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout resultPaneLayout = new javax.swing.GroupLayout(resultPane);
        resultPane.setLayout(resultPaneLayout);
        resultPaneLayout.setHorizontalGroup(
            resultPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
        );
        resultPaneLayout.setVerticalGroup(
            resultPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resultPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
        );

        promptPane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 2, true));
        promptPane.setLayout(new java.awt.CardLayout());

        enterIDLabel.setText("Enter Tool ID:");
        enterIDLabel.setToolTipText("");
        enterIDLabel.setLocation(new java.awt.Point(-32689, -32520));
        enterIDLabel.setMaximumSize(new java.awt.Dimension(108, 16));
        enterIDLabel.setMinimumSize(new java.awt.Dimension(108, 16));

        enterIDField.setLocation(new java.awt.Point(-32721, -32492));

        enterIDSubmit.setText("Submit");
        enterIDSubmit.setLocation(new java.awt.Point(-32730, -32312));

        javax.swing.GroupLayout promptIDPaneLayout = new javax.swing.GroupLayout(promptIDPane);
        promptIDPane.setLayout(promptIDPaneLayout);
        promptIDPaneLayout.setHorizontalGroup(
            promptIDPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(promptIDPaneLayout.createSequentialGroup()
                .addGroup(promptIDPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(promptIDPaneLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(enterIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(promptIDPaneLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(enterIDSubmit))
                    .addGroup(promptIDPaneLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(enterIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        promptIDPaneLayout.setVerticalGroup(
            promptIDPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(promptIDPaneLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(enterIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterIDSubmit)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        promptPane.add(promptIDPane, "card2");

        promptNameLabel.setText("Enter Tool Name:");

        promptNameSubmit.setText("Submit");
       

        javax.swing.GroupLayout promptNamePaneLayout = new javax.swing.GroupLayout(promptNamePane);
        promptNamePane.setLayout(promptNamePaneLayout);
        promptNamePaneLayout.setHorizontalGroup(
            promptNamePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, promptNamePaneLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(promptNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(promptNamePaneLayout.createSequentialGroup()
                .addGroup(promptNamePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(promptNamePaneLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(promptNameLabel))
                    .addGroup(promptNamePaneLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(promptNameSubmit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        promptNamePaneLayout.setVerticalGroup(
            promptNamePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(promptNamePaneLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(promptNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(promptNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(promptNameSubmit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        promptPane.add(promptNamePane, "card3");

        promptToolLabel.setText("Enter Tool ID:");

        promptQtySubmit.setText("Submit");
        

        promptQtyLabel.setText("Enter Quantity");

        javax.swing.GroupLayout promptQtyPaneLayout = new javax.swing.GroupLayout(promptQtyPane);
        promptQtyPane.setLayout(promptQtyPaneLayout);
        promptQtyPaneLayout.setHorizontalGroup(
            promptQtyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(promptQtyPaneLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(promptQtyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(promptQtyField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(promptToolField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, promptQtyPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(promptQtyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, promptQtyPaneLayout.createSequentialGroup()
                        .addComponent(promptToolLabel)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, promptQtyPaneLayout.createSequentialGroup()
                        .addComponent(promptQtySubmit)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, promptQtyPaneLayout.createSequentialGroup()
                        .addComponent(promptQtyLabel)
                        .addGap(56, 56, 56))))
        );
        promptQtyPaneLayout.setVerticalGroup(
            promptQtyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(promptQtyPaneLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(promptToolLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(promptToolField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(promptQtyLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(promptQtyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(promptQtySubmit)
                .addGap(72, 72, 72))
        );

        promptPane.add(promptQtyPane, "card3");

        aDName.setText("Name:");

        deleteButton.setText("Delete");
        

        addButton.setText("Add");
        

        aDID.setText("ID:");

        aDQty.setText("Qty:");

        aDType.setText("Type:");

        aDPrice.setText("Price:");

        aDSupply.setText("Suppl.");

        aDPower.setText("Power:");

        javax.swing.GroupLayout addDeletePanelLayout = new javax.swing.GroupLayout(addDeletePanel);
        addDeletePanel.setLayout(addDeletePanelLayout);
        addDeletePanelLayout.setHorizontalGroup(
            addDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDeletePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addDeletePanelLayout.createSequentialGroup()
                        .addComponent(addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteButton))
                    .addGroup(addDeletePanelLayout.createSequentialGroup()
                        .addGroup(addDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addDeletePanelLayout.createSequentialGroup()
                                .addGroup(addDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(aDName)
                                    .addComponent(aDSupply))
                                .addGap(18, 18, 18)
                                .addGroup(addDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(adNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(aDSupplyField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(addDeletePanelLayout.createSequentialGroup()
                                .addComponent(aDID)
                                .addGap(18, 18, 18)
                                .addComponent(aDIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(aDType)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(aDTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addDeletePanelLayout.createSequentialGroup()
                                .addGroup(addDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(aDQty)
                                    .addComponent(aDPower)
                                    .addComponent(aDPrice))
                                .addGap(18, 18, 18)
                                .addGroup(addDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(aDPowerField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adQtyField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(aDPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        addDeletePanelLayout.setVerticalGroup(
            addDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDeletePanelLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(addDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aDName)
                    .addComponent(adNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aDID)
                    .addComponent(aDIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aDType)
                    .addComponent(aDTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aDPower)
                    .addComponent(aDPowerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aDQty)
                    .addComponent(adQtyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(aDPrice)
                    .addComponent(aDPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(addDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aDSupplyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aDSupply))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteButton)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addDeletePanelLayout.createSequentialGroup()
                        .addComponent(addButton)
                        .addContainerGap())))
        );

        promptPane.add(addDeletePanel, "card3");

        messagePane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 2, true));

        messageLabel.setText("Message:");

        messageBox.setColumns(20);
        messageBox.setRows(5);
        messageArea.setViewportView(messageBox);

        javax.swing.GroupLayout messagePaneLayout = new javax.swing.GroupLayout(messagePane);
        messagePane.setLayout(messagePaneLayout);
        messagePaneLayout.setHorizontalGroup(
            messagePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messagePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(messagePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(messageArea)
                    .addGroup(messagePaneLayout.createSequentialGroup()
                        .addComponent(messageLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        messagePaneLayout.setVerticalGroup(
            messagePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messagePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(messageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messageArea)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolBanner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(optionPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(promptPane))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(messagePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolBanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(optionPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(promptPane, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(resultPane, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(messagePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 

    public javax.swing.JLabel getaDID() {
		return aDID;
	}

	public void setaDID(javax.swing.JLabel aDID) {
		this.aDID = aDID;
	}

	public javax.swing.JTextField getaDIDField() {
		return aDIDField;
	}

	public void setaDIDField(javax.swing.JTextField aDIDField) {
		this.aDIDField = aDIDField;
	}

	public javax.swing.JLabel getaDName() {
		return aDName;
	}

	public void setaDName(javax.swing.JLabel aDName) {
		this.aDName = aDName;
	}

	public javax.swing.JLabel getaDPower() {
		return aDPower;
	}

	public void setaDPower(javax.swing.JLabel aDPower) {
		this.aDPower = aDPower;
	}

	public javax.swing.JTextField getaDPowerField() {
		return aDPowerField;
	}

	public void setaDPowerField(javax.swing.JTextField aDPowerField) {
		this.aDPowerField = aDPowerField;
	}

	public javax.swing.JLabel getaDPrice() {
		return aDPrice;
	}

	public void setaDPrice(javax.swing.JLabel aDPrice) {
		this.aDPrice = aDPrice;
	}

	public javax.swing.JTextField getaDPriceField() {
		return aDPriceField;
	}

	public void setaDPriceField(javax.swing.JTextField aDPriceField) {
		this.aDPriceField = aDPriceField;
	}

	public javax.swing.JLabel getaDQty() {
		return aDQty;
	}

	public void setaDQty(javax.swing.JLabel aDQty) {
		this.aDQty = aDQty;
	}

	public javax.swing.JLabel getaDSupply() {
		return aDSupply;
	}

	public void setaDSupply(javax.swing.JLabel aDSupply) {
		this.aDSupply = aDSupply;
	}

	public javax.swing.JTextField getaDSupplyField() {
		return aDSupplyField;
	}

	public void setaDSupplyField(javax.swing.JTextField aDSupplyField) {
		this.aDSupplyField = aDSupplyField;
	}

	public javax.swing.JLabel getaDType() {
		return aDType;
	}

	public void setaDType(javax.swing.JLabel aDType) {
		this.aDType = aDType;
	}

	public javax.swing.JTextField getaDTypeField() {
		return aDTypeField;
	}

	public void setaDTypeField(javax.swing.JTextField aDTypeField) {
		this.aDTypeField = aDTypeField;
	}

	public javax.swing.JTextField getAdNameField() {
		return adNameField;
	}

	public void setAdNameField(javax.swing.JTextField adNameField) {
		this.adNameField = adNameField;
	}

	public javax.swing.JTextField getAdQtyField() {
		return adQtyField;
	}

	public void setAdQtyField(javax.swing.JTextField adQtyField) {
		this.adQtyField = adQtyField;
	}

	public javax.swing.JButton getAddButton() {
		return addButton;
	}

	public void setAddButton(javax.swing.JButton addButton) {
		this.addButton = addButton;
	}

	public javax.swing.JButton getAddDeleteButton() {
		return addDeleteButton;
	}

	public void setAddDeleteButton(javax.swing.JButton addDeleteButton) {
		this.addDeleteButton = addDeleteButton;
	}

	public javax.swing.JPanel getAddDeletePanel() {
		return addDeletePanel;
	}

	public void setAddDeletePanel(javax.swing.JPanel addDeletePanel) {
		this.addDeletePanel = addDeletePanel;
	}

	public javax.swing.JButton getDecreaseButton() {
		return decreaseButton;
	}

	public void setDecreaseButton(javax.swing.JButton decreaseButton) {
		this.decreaseButton = decreaseButton;
	}

	public javax.swing.JButton getDeleteButton() {
		return deleteButton;
	}

	public void setDeleteButton(javax.swing.JButton deleteButton) {
		this.deleteButton = deleteButton;
	}

	public javax.swing.JTextField getEnterIDField() {
		return enterIDField;
	}

	public void setEnterIDField(javax.swing.JTextField enterIDField) {
		this.enterIDField = enterIDField;
	}

	public javax.swing.JLabel getEnterIDLabel() {
		return enterIDLabel;
	}

	public void setEnterIDLabel(javax.swing.JLabel enterIDLabel) {
		this.enterIDLabel = enterIDLabel;
	}

	public javax.swing.JButton getEnterIDSubmit() {
		return enterIDSubmit;
	}

	public void setEnterIDSubmit(javax.swing.JButton enterIDSubmit) {
		this.enterIDSubmit = enterIDSubmit;
	}

	public javax.swing.JScrollPane getjScrollPane2() {
		return jScrollPane2;
	}

	public void setjScrollPane2(javax.swing.JScrollPane jScrollPane2) {
		this.jScrollPane2 = jScrollPane2;
	}

	public javax.swing.JTextArea getMessageBox() {
		return messageBox;
	}

	public void setMessageBox(javax.swing.JTextArea jTextArea1) {
		this.messageBox = jTextArea1;
	}

	public javax.swing.JButton getListAllButton() {
		return listAllButton;
	}

	public void setListAllButton(javax.swing.JButton listAllButton) {
		this.listAllButton = listAllButton;
	}

	public javax.swing.JScrollPane getMessageArea() {
		return messageArea;
	}

	public void setMessageArea(javax.swing.JScrollPane messageArea) {
		this.messageArea = messageArea;
	}

	public javax.swing.JLabel getMessageLabel() {
		return messageLabel;
	}

	public void setMessageLabel(javax.swing.JLabel messageLabel) {
		this.messageLabel = messageLabel;
	}

	public javax.swing.JPanel getMessagePane() {
		return messagePane;
	}

	public void setMessagePane(javax.swing.JPanel messagePane) {
		this.messagePane = messagePane;
	}

	public javax.swing.JPanel getOptionPane() {
		return optionPane;
	}

	public void setOptionPane(javax.swing.JPanel optionPane) {
		this.optionPane = optionPane;
	}

	public javax.swing.JPanel getPromptIDPane() {
		return promptIDPane;
	}

	public void setPromptIDPane(javax.swing.JPanel promptIDPane) {
		this.promptIDPane = promptIDPane;
	}

	public javax.swing.JTextField getPromptNameField() {
		return promptNameField;
	}

	public void setPromptNameField(javax.swing.JTextField promptNameField) {
		this.promptNameField = promptNameField;
	}

	public javax.swing.JLabel getPromptNameLabel() {
		return promptNameLabel;
	}

	public void setPromptNameLabel(javax.swing.JLabel promptNameLabel) {
		this.promptNameLabel = promptNameLabel;
	}

	public javax.swing.JPanel getPromptNamePane() {
		return promptNamePane;
	}

	public void setPromptNamePane(javax.swing.JPanel promptNamePane) {
		this.promptNamePane = promptNamePane;
	}

	public javax.swing.JButton getPromptNameSubmit() {
		return promptNameSubmit;
	}

	public void setPromptNameSubmit(javax.swing.JButton promptNameSubmit) {
		this.promptNameSubmit = promptNameSubmit;
	}

	public javax.swing.JLayeredPane getPromptPane() {
		return promptPane;
	}

	public void setPromptPane(javax.swing.JLayeredPane promptPane) {
		this.promptPane = promptPane;
	}

	public javax.swing.JTextField getPromptQtyField() {
		return promptQtyField;
	}

	public void setPromptQtyField(javax.swing.JTextField promptQtyField) {
		this.promptQtyField = promptQtyField;
	}

	public javax.swing.JLabel getPromptQtyLabel() {
		return promptQtyLabel;
	}

	public void setPromptQtyLabel(javax.swing.JLabel promptQtyLabel) {
		this.promptQtyLabel = promptQtyLabel;
	}

	public javax.swing.JPanel getPromptQtyPane() {
		return promptQtyPane;
	}

	public void setPromptQtyPane(javax.swing.JPanel promptQtyPane) {
		this.promptQtyPane = promptQtyPane;
	}

	public javax.swing.JButton getPromptQtySubmit() {
		return promptQtySubmit;
	}

	public void setPromptQtySubmit(javax.swing.JButton promptQtySubmit) {
		this.promptQtySubmit = promptQtySubmit;
	}

	public javax.swing.JTextField getPromptToolField() {
		return promptToolField;
	}

	public void setPromptToolField(javax.swing.JTextField promptToolField) {
		this.promptToolField = promptToolField;
	}

	public javax.swing.JLabel getPromptToolLabel() {
		return promptToolLabel;
	}

	public void setPromptToolLabel(javax.swing.JLabel promptToolLabel) {
		this.promptToolLabel = promptToolLabel;
	}

	public javax.swing.JLabel getResultLabel() {
		return resultLabel;
	}

	public void setResultLabel(javax.swing.JLabel resultLabel) {
		this.resultLabel = resultLabel;
	}

	public javax.swing.JPanel getResultPane() {
		return resultPane;
	}

	public void setResultPane(javax.swing.JPanel resultPane) {
		this.resultPane = resultPane;
	}

	public javax.swing.JTable getResultTable() {
		return resultTable;
	}

	public void setResultTable(javax.swing.JTable resultTable) {
		this.resultTable = resultTable;
	}

	public javax.swing.JButton getSearchIDButton() {
		return searchIDButton;
	}

	public void setSearchIDButton(javax.swing.JButton searchIDButton) {
		this.searchIDButton = searchIDButton;
	}

	public javax.swing.JButton getSearchNameButton() {
		return searchNameButton;
	}

	public void setSearchNameButton(javax.swing.JButton searchNameButton) {
		this.searchNameButton = searchNameButton;
	}

	public javax.swing.JButton getSearchQuantButton() {
		return searchQuantButton;
	}

	public void setSearchQuantButton(javax.swing.JButton searchQuantButton) {
		this.searchQuantButton = searchQuantButton;
	}

	public javax.swing.JPanel getToolBanner() {
		return toolBanner;
	}

	public void setToolBanner(javax.swing.JPanel toolBanner) {
		this.toolBanner = toolBanner;
	}

	public javax.swing.JLabel getToolBannerLabel() {
		return toolBannerLabel;
	}

	public void setToolBannerLabel(javax.swing.JLabel toolBannerLabel) {
		this.toolBannerLabel = toolBannerLabel;
	}



	// Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aDID;
    private javax.swing.JTextField aDIDField;
    private javax.swing.JLabel aDName;
    private javax.swing.JLabel aDPower;
    private javax.swing.JTextField aDPowerField;
    private javax.swing.JLabel aDPrice;
    private javax.swing.JTextField aDPriceField;
    private javax.swing.JLabel aDQty;
    private javax.swing.JLabel aDSupply;
    private javax.swing.JTextField aDSupplyField;
    private javax.swing.JLabel aDType;
    private javax.swing.JTextField aDTypeField;
    private javax.swing.JTextField adNameField;
    private javax.swing.JTextField adQtyField;
    private javax.swing.JButton addButton;
    private javax.swing.JButton addDeleteButton;
    private javax.swing.JPanel addDeletePanel;
    private javax.swing.JButton decreaseButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField enterIDField;
    private javax.swing.JLabel enterIDLabel;
    private javax.swing.JButton enterIDSubmit;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea messageBox;
    private javax.swing.JButton listAllButton;
    private javax.swing.JScrollPane messageArea;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JPanel messagePane;
    private javax.swing.JPanel optionPane;
    private javax.swing.JPanel promptIDPane;
    private javax.swing.JTextField promptNameField;
    private javax.swing.JLabel promptNameLabel;
    private javax.swing.JPanel promptNamePane;
    private javax.swing.JButton promptNameSubmit;
    private javax.swing.JLayeredPane promptPane;
    private javax.swing.JTextField promptQtyField;
    private javax.swing.JLabel promptQtyLabel;
    private javax.swing.JPanel promptQtyPane;
    private javax.swing.JButton promptQtySubmit;
    private javax.swing.JTextField promptToolField;
    private javax.swing.JLabel promptToolLabel;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JPanel resultPane;
    private javax.swing.JTable resultTable;
    private javax.swing.JButton searchIDButton;
    private javax.swing.JButton searchNameButton;
    private javax.swing.JButton searchQuantButton;
    private javax.swing.JPanel toolBanner;
    private javax.swing.JLabel toolBannerLabel;
    // End of variables declaration//GEN-END:variables
    public void addButtonListener(ActionListener listAll,ActionListener searchName,ActionListener searchId,
			ActionListener searchQty, ActionListener decrease,ActionListener addRemove, ActionListener submitName,ActionListener submitID,
			ActionListener submitQty,ActionListener submitAdd,ActionListener submitDelete) {
		listAllButton.addActionListener(listAll);
		searchNameButton.addActionListener(searchName);
		searchIDButton.addActionListener(searchId);
		searchQuantButton.addActionListener(searchQty);
		decreaseButton.addActionListener(decrease);
		addDeleteButton.addActionListener(addRemove);
		promptNameSubmit.addActionListener(submitName);
		enterIDSubmit.addActionListener(submitID);
		promptQtySubmit.addActionListener(submitQty);
		addButton.addActionListener(submitAdd);
		deleteButton.addActionListener(submitDelete);
    }
}
