package Client.View;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author thiennguyen
 */
public class ToolGUI extends javax.swing.JFrame {

    /**
     * Creates new form ToolGUI
     */
    public ToolGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolBanner = new javax.swing.JPanel();
        toolBannerLabel = new javax.swing.JLabel();
        optionPane = new javax.swing.JPanel();
        listAllButton = new javax.swing.JButton();
        searchNameButton = new javax.swing.JButton();
        searchIDButton = new javax.swing.JButton();
        searchQuantButton = new javax.swing.JButton();
        decreaseButton = new javax.swing.JButton();
        addDeleteButton = new javax.swing.JButton();
        resultPane = new javax.swing.JPanel();
        resultLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();
        promptPane = new javax.swing.JLayeredPane();
        promptIDPane = new javax.swing.JPanel();
        enterIDLabel = new javax.swing.JLabel();
        enterIDField = new javax.swing.JTextField();
        enterIDSubmit = new javax.swing.JButton();
        promptNamePane = new javax.swing.JPanel();
        promptNameLabel = new javax.swing.JLabel();
        promptNameField = new javax.swing.JTextField();
        promptNameSubmit = new javax.swing.JButton();
        promptQtyPane = new javax.swing.JPanel();
        promptToolLabel = new javax.swing.JLabel();
        promptToolField = new javax.swing.JTextField();
        promptQtySubmit = new javax.swing.JButton();
        promptQtyLabel = new javax.swing.JLabel();
        promptQtyField = new javax.swing.JTextField();
        addDeletePanel = new javax.swing.JPanel();
        aDName = new javax.swing.JLabel();
        adNameField = new javax.swing.JTextField();
        deleteButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        aDID = new javax.swing.JLabel();
        aDIDField = new javax.swing.JTextField();
        aDQty = new javax.swing.JLabel();
        aDTypeField = new javax.swing.JTextField();
        aDType = new javax.swing.JLabel();
        adQtyField = new javax.swing.JTextField();
        aDPrice = new javax.swing.JLabel();
        aDPriceField = new javax.swing.JTextField();
        aDSupply = new javax.swing.JLabel();
        aDSupplyField = new javax.swing.JTextField();
        aDPower = new javax.swing.JLabel();
        aDPowerField = new javax.swing.JTextField();
        messagePane = new javax.swing.JPanel();
        messageLabel = new javax.swing.JLabel();
        messageArea = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        toolBanner.setBackground(new java.awt.Color(153, 153, 255));

        toolBannerLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        toolBannerLabel.setText("Inventory Management System");

        javax.swing.GroupLayout toolBannerLayout = new javax.swing.GroupLayout(toolBanner);
        toolBanner.setLayout(toolBannerLayout);
        toolBannerLayout.setHorizontalGroup(
            toolBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolBannerLayout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(toolBannerLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        toolBannerLayout.setVerticalGroup(
            toolBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolBannerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(toolBannerLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        optionPane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 2, true));

        listAllButton.setText("List All Tools");

        searchNameButton.setText("Search by Tool Name");

        searchIDButton.setText("Search by Tool ID");

        searchQuantButton.setText("Check Tool Quantity");

        decreaseButton.setText("Decrease Item Quantity");

        addDeleteButton.setText("Add/Delete Item");

        javax.swing.GroupLayout optionPaneLayout = new javax.swing.GroupLayout(optionPane);
        optionPane.setLayout(optionPaneLayout);
        optionPaneLayout.setHorizontalGroup(
            optionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPaneLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(optionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(decreaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchQuantButton)
                    .addComponent(searchIDButton, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(optionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(searchNameButton)
                        .addComponent(listAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        optionPaneLayout.setVerticalGroup(
            optionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listAllButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchNameButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchIDButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchQuantButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(decreaseButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addDeleteButton)
                .addGap(12, 12, 12))
        );

        resultPane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 2, true));

        resultLabel.setText("Result:");

        resultTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        resultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tool_id", "Name", "Type", "Quantity", "Price", "Supplier_id", "Power"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(resultTable);
        if (resultTable.getColumnModel().getColumnCount() > 0) {
            resultTable.getColumnModel().getColumn(2).setResizable(false);
            resultTable.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout resultPaneLayout = new javax.swing.GroupLayout(resultPane);
        resultPane.setLayout(resultPaneLayout);
        resultPaneLayout.setHorizontalGroup(
            resultPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
        );
        resultPaneLayout.setVerticalGroup(
            resultPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resultPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
        );

        promptPane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 2, true));
        promptPane.setLayout(new java.awt.CardLayout());

        enterIDLabel.setText("Enter Tool ID:");
        enterIDLabel.setToolTipText("");
        enterIDLabel.setLocation(new java.awt.Point(-32689, -32520));
        enterIDLabel.setMaximumSize(new java.awt.Dimension(108, 16));
        enterIDLabel.setMinimumSize(new java.awt.Dimension(108, 16));

        enterIDField.setLocation(new java.awt.Point(-32721, -32492));

        enterIDSubmit.setText("Submit");
        enterIDSubmit.setLocation(new java.awt.Point(-32730, -32312));

        javax.swing.GroupLayout promptIDPaneLayout = new javax.swing.GroupLayout(promptIDPane);
        promptIDPane.setLayout(promptIDPaneLayout);
        promptIDPaneLayout.setHorizontalGroup(
            promptIDPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(promptIDPaneLayout.createSequentialGroup()
                .addGroup(promptIDPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(promptIDPaneLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(enterIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(promptIDPaneLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(enterIDSubmit))
                    .addGroup(promptIDPaneLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(enterIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        promptIDPaneLayout.setVerticalGroup(
            promptIDPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(promptIDPaneLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(enterIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterIDSubmit)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        promptPane.add(promptIDPane, "card2");

        promptNameLabel.setText("Enter Tool Name:");

        promptNameSubmit.setText("Submit");
        promptNameSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promptNameSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout promptNamePaneLayout = new javax.swing.GroupLayout(promptNamePane);
        promptNamePane.setLayout(promptNamePaneLayout);
        promptNamePaneLayout.setHorizontalGroup(
            promptNamePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, promptNamePaneLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(promptNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(promptNamePaneLayout.createSequentialGroup()
                .addGroup(promptNamePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(promptNamePaneLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(promptNameLabel))
                    .addGroup(promptNamePaneLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(promptNameSubmit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        promptNamePaneLayout.setVerticalGroup(
            promptNamePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(promptNamePaneLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(promptNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(promptNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(promptNameSubmit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        promptPane.add(promptNamePane, "card3");

        promptToolLabel.setText("Enter Tool Name:");

        promptQtySubmit.setText("Submit");
        promptQtySubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promptQtySubmitActionPerformed(evt);
            }
        });

        promptQtyLabel.setText("Enter Quantity");

        javax.swing.GroupLayout promptQtyPaneLayout = new javax.swing.GroupLayout(promptQtyPane);
        promptQtyPane.setLayout(promptQtyPaneLayout);
        promptQtyPaneLayout.setHorizontalGroup(
            promptQtyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(promptQtyPaneLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(promptQtyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(promptQtyField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(promptToolField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, promptQtyPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(promptQtyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, promptQtyPaneLayout.createSequentialGroup()
                        .addComponent(promptToolLabel)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, promptQtyPaneLayout.createSequentialGroup()
                        .addComponent(promptQtySubmit)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, promptQtyPaneLayout.createSequentialGroup()
                        .addComponent(promptQtyLabel)
                        .addGap(56, 56, 56))))
        );
        promptQtyPaneLayout.setVerticalGroup(
            promptQtyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(promptQtyPaneLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(promptToolLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(promptToolField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(promptQtyLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(promptQtyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(promptQtySubmit)
                .addGap(72, 72, 72))
        );

        promptPane.add(promptQtyPane, "card3");

        aDName.setText("Name:");

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        aDID.setText("ID:");

        aDQty.setText("Qty:");

        aDType.setText("Type:");

        aDPrice.setText("Price:");

        aDSupply.setText("Suppl.");

        aDPower.setText("Power:");

        javax.swing.GroupLayout addDeletePanelLayout = new javax.swing.GroupLayout(addDeletePanel);
        addDeletePanel.setLayout(addDeletePanelLayout);
        addDeletePanelLayout.setHorizontalGroup(
            addDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDeletePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addDeletePanelLayout.createSequentialGroup()
                        .addComponent(addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteButton))
                    .addGroup(addDeletePanelLayout.createSequentialGroup()
                        .addGroup(addDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addDeletePanelLayout.createSequentialGroup()
                                .addGroup(addDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(aDName)
                                    .addComponent(aDSupply))
                                .addGap(18, 18, 18)
                                .addGroup(addDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(adNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(aDSupplyField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(addDeletePanelLayout.createSequentialGroup()
                                .addComponent(aDID)
                                .addGap(18, 18, 18)
                                .addComponent(aDIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(aDType)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(aDTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addDeletePanelLayout.createSequentialGroup()
                                .addGroup(addDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(aDQty)
                                    .addComponent(aDPower)
                                    .addComponent(aDPrice))
                                .addGap(18, 18, 18)
                                .addGroup(addDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(aDPowerField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adQtyField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(aDPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        addDeletePanelLayout.setVerticalGroup(
            addDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDeletePanelLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(addDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aDName)
                    .addComponent(adNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aDID)
                    .addComponent(aDIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aDType)
                    .addComponent(aDTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aDPower)
                    .addComponent(aDPowerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aDQty)
                    .addComponent(adQtyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(aDPrice)
                    .addComponent(aDPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(addDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aDSupplyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aDSupply))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteButton)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addDeletePanelLayout.createSequentialGroup()
                        .addComponent(addButton)
                        .addContainerGap())))
        );

        promptPane.add(addDeletePanel, "card3");

        messagePane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 2, true));

        messageLabel.setText("Message:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        messageArea.setViewportView(jTextArea1);

        javax.swing.GroupLayout messagePaneLayout = new javax.swing.GroupLayout(messagePane);
        messagePane.setLayout(messagePaneLayout);
        messagePaneLayout.setHorizontalGroup(
            messagePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messagePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(messagePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(messageArea)
                    .addGroup(messagePaneLayout.createSequentialGroup()
                        .addComponent(messageLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        messagePaneLayout.setVerticalGroup(
            messagePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messagePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(messageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messageArea)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolBanner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(optionPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(promptPane))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(messagePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolBanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(optionPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(promptPane, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(resultPane, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(messagePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void promptNameSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promptNameSubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_promptNameSubmitActionPerformed

    private void promptQtySubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promptQtySubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_promptQtySubmitActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ToolGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ToolGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ToolGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ToolGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ToolGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aDID;
    private javax.swing.JTextField aDIDField;
    private javax.swing.JLabel aDName;
    private javax.swing.JLabel aDPower;
    private javax.swing.JTextField aDPowerField;
    private javax.swing.JLabel aDPrice;
    private javax.swing.JTextField aDPriceField;
    private javax.swing.JLabel aDQty;
    private javax.swing.JLabel aDSupply;
    private javax.swing.JTextField aDSupplyField;
    private javax.swing.JLabel aDType;
    private javax.swing.JTextField aDTypeField;
    private javax.swing.JTextField adNameField;
    private javax.swing.JTextField adQtyField;
    private javax.swing.JButton addButton;
    private javax.swing.JButton addDeleteButton;
    private javax.swing.JPanel addDeletePanel;
    private javax.swing.JButton decreaseButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField enterIDField;
    private javax.swing.JLabel enterIDLabel;
    private javax.swing.JButton enterIDSubmit;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton listAllButton;
    private javax.swing.JScrollPane messageArea;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JPanel messagePane;
    private javax.swing.JPanel optionPane;
    private javax.swing.JPanel promptIDPane;
    private javax.swing.JTextField promptNameField;
    private javax.swing.JLabel promptNameLabel;
    private javax.swing.JPanel promptNamePane;
    private javax.swing.JButton promptNameSubmit;
    private javax.swing.JLayeredPane promptPane;
    private javax.swing.JTextField promptQtyField;
    private javax.swing.JLabel promptQtyLabel;
    private javax.swing.JPanel promptQtyPane;
    private javax.swing.JButton promptQtySubmit;
    private javax.swing.JTextField promptToolField;
    private javax.swing.JLabel promptToolLabel;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JPanel resultPane;
    private javax.swing.JTable resultTable;
    private javax.swing.JButton searchIDButton;
    private javax.swing.JButton searchNameButton;
    private javax.swing.JButton searchQuantButton;
    private javax.swing.JPanel toolBanner;
    private javax.swing.JLabel toolBannerLabel;
    // End of variables declaration//GEN-END:variables
}
